version: "3.8"

services:
  logger:
    build: .
    container_name: kotlin_logger
    environment:
      LOG_PATH_CONTAINER: ${LOG_PATH_CONTAINER}
    volumes:
      - ${LOG_PATH_HOST}:${LOG_PATH_CONTAINER}