version: "3.8"

services:
  kotlin_logger123:
    build: .
    container_name: kotlin_logger456
    environment:
      LOG_PATH_CONTAINER: ${LOG_PATH_CONTAINER}
    volumes:
      - ${LOG_PATH_HOST}:${LOG_PATH_CONTAINER}